version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - storage_data:/var/www/html/storage/app/public

  db:
    image: postgres:15-alpine
    container_name: postgres_db_prod
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg_data_prod:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_storage_prod
    restart: unless-stopped

volumes:
  pg_data_prod:
  storage_data:
